// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DetectionEvent {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
    #[prost(string, tag = "2")]
    pub detector_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(double, tag = "4")]
    pub x: f64,
    #[prost(double, tag = "5")]
    pub y: f64,
    #[prost(double, tag = "6")]
    pub z: f64,
    #[prost(double, tag = "7")]
    pub confidence: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsensusAction {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
    #[prost(string, tag = "2")]
    pub sender_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub action_type: ::prost::alloc::string::String,
    #[prost(double, repeated, tag = "4")]
    pub params: ::prost::alloc::vec::Vec<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DroneMessage {
    #[prost(oneof = "drone_message::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<drone_message::Payload>,
}
/// Nested message and enum types in `DroneMessage`.
pub mod drone_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        Detection(super::DetectionEvent),
        #[prost(message, tag = "2")]
        Consensus(super::ConsensusAction),
    }
}
