name: nix

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Nix formatting
        run: |
          nix fmt --accept-flake-config -- --check .

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check Rust formatting
        run: cargo fmt -- --check
