name: ros2

on:
  push:
    branches: [ "main" ]
    paths: [ "ros2/**.yaml" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-ros2:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup ROS 2 Jazzy
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Parse YAML configuration
        run: |
            source /opt/ros/jazzy/setup.bash

            shopt -s nullglob
            for file in ros2/*.yaml; do
                echo "Checking structure of $file..."
                ros2 param dump --file "$file" --dry-run
            done
